<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Places extends \AppBundle\Entity\Places implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Places' . "\0" . 'creDat', '' . "\0" . 'AppBundle\\Entity\\Places' . "\0" . 'creUser', '' . "\0" . 'AppBundle\\Entity\\Places' . "\0" . 'modDat', '' . "\0" . 'AppBundle\\Entity\\Places' . "\0" . 'modUser', '' . "\0" . 'AppBundle\\Entity\\Places' . "\0" . 'name', '' . "\0" . 'AppBundle\\Entity\\Places' . "\0" . 'type', '' . "\0" . 'AppBundle\\Entity\\Places' . "\0" . 'seqno', '' . "\0" . 'AppBundle\\Entity\\Places' . "\0" . 'pceSeqno');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Places' . "\0" . 'creDat', '' . "\0" . 'AppBundle\\Entity\\Places' . "\0" . 'creUser', '' . "\0" . 'AppBundle\\Entity\\Places' . "\0" . 'modDat', '' . "\0" . 'AppBundle\\Entity\\Places' . "\0" . 'modUser', '' . "\0" . 'AppBundle\\Entity\\Places' . "\0" . 'name', '' . "\0" . 'AppBundle\\Entity\\Places' . "\0" . 'type', '' . "\0" . 'AppBundle\\Entity\\Places' . "\0" . 'seqno', '' . "\0" . 'AppBundle\\Entity\\Places' . "\0" . 'pceSeqno');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Places $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setCreDat($creDat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreDat', array($creDat));

        return parent::setCreDat($creDat);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreDat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreDat', array());

        return parent::getCreDat();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreUser($creUser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreUser', array($creUser));

        return parent::setCreUser($creUser);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreUser', array());

        return parent::getCreUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setModDat($modDat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModDat', array($modDat));

        return parent::setModDat($modDat);
    }

    /**
     * {@inheritDoc}
     */
    public function getModDat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModDat', array());

        return parent::getModDat();
    }

    /**
     * {@inheritDoc}
     */
    public function setModUser($modUser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModUser', array($modUser));

        return parent::setModUser($modUser);
    }

    /**
     * {@inheritDoc}
     */
    public function getModUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModUser', array());

        return parent::getModUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', array($type));

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', array());

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function getSeqno()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getSeqno();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeqno', array());

        return parent::getSeqno();
    }

    /**
     * {@inheritDoc}
     */
    public function setPceSeqno(\AppBundle\Entity\Places $pceSeqno = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPceSeqno', array($pceSeqno));

        return parent::setPceSeqno($pceSeqno);
    }

    /**
     * {@inheritDoc}
     */
    public function getPceSeqno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPceSeqno', array());

        return parent::getPceSeqno();
    }

    /**
     * {@inheritDoc}
     */
    public function getParentName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParentName', array());

        return parent::getParentName();
    }

    /**
     * {@inheritDoc}
     */
    public function getFullyQualifiedName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFullyQualifiedName', array());

        return parent::getFullyQualifiedName();
    }

}
