<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EventStates extends \AppBundle\Entity\EventStates implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\EventStates' . "\0" . 'creDat', '' . "\0" . 'AppBundle\\Entity\\EventStates' . "\0" . 'creUser', '' . "\0" . 'AppBundle\\Entity\\EventStates' . "\0" . 'description', '' . "\0" . 'AppBundle\\Entity\\EventStates' . "\0" . 'eventDatetime', '' . "\0" . 'AppBundle\\Entity\\EventStates' . "\0" . 'eventDatetimeFlag', '' . "\0" . 'AppBundle\\Entity\\EventStates' . "\0" . 'modDat', '' . "\0" . 'AppBundle\\Entity\\EventStates' . "\0" . 'modUser', '' . "\0" . 'AppBundle\\Entity\\EventStates' . "\0" . 'seqno', '' . "\0" . 'AppBundle\\Entity\\EventStates' . "\0" . 'clnSeqno', '' . "\0" . 'AppBundle\\Entity\\EventStates' . "\0" . 'spec2event', '' . "\0" . 'AppBundle\\Entity\\EventStates' . "\0" . 'event2Persons');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\EventStates' . "\0" . 'creDat', '' . "\0" . 'AppBundle\\Entity\\EventStates' . "\0" . 'creUser', '' . "\0" . 'AppBundle\\Entity\\EventStates' . "\0" . 'description', '' . "\0" . 'AppBundle\\Entity\\EventStates' . "\0" . 'eventDatetime', '' . "\0" . 'AppBundle\\Entity\\EventStates' . "\0" . 'eventDatetimeFlag', '' . "\0" . 'AppBundle\\Entity\\EventStates' . "\0" . 'modDat', '' . "\0" . 'AppBundle\\Entity\\EventStates' . "\0" . 'modUser', '' . "\0" . 'AppBundle\\Entity\\EventStates' . "\0" . 'seqno', '' . "\0" . 'AppBundle\\Entity\\EventStates' . "\0" . 'clnSeqno', '' . "\0" . 'AppBundle\\Entity\\EventStates' . "\0" . 'spec2event', '' . "\0" . 'AppBundle\\Entity\\EventStates' . "\0" . 'event2Persons');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (EventStates $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setCreDat($creDat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreDat', array($creDat));

        return parent::setCreDat($creDat);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreDat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreDat', array());

        return parent::getCreDat();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreUser($creUser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreUser', array($creUser));

        return parent::setCreUser($creUser);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreUser', array());

        return parent::getCreUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setEventDatetime($eventDatetime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEventDatetime', array($eventDatetime));

        return parent::setEventDatetime($eventDatetime);
    }

    /**
     * {@inheritDoc}
     */
    public function getEventDatetime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventDatetime', array());

        return parent::getEventDatetime();
    }

    /**
     * {@inheritDoc}
     */
    public function setEventDatetimeFlag($eventDatetimeFlag)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEventDatetimeFlag', array($eventDatetimeFlag));

        return parent::setEventDatetimeFlag($eventDatetimeFlag);
    }

    /**
     * {@inheritDoc}
     */
    public function getEventDatetimeFlag()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventDatetimeFlag', array());

        return parent::getEventDatetimeFlag();
    }

    /**
     * {@inheritDoc}
     */
    public function setModDat($modDat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModDat', array($modDat));

        return parent::setModDat($modDat);
    }

    /**
     * {@inheritDoc}
     */
    public function getModDat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModDat', array());

        return parent::getModDat();
    }

    /**
     * {@inheritDoc}
     */
    public function setModUser($modUser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModUser', array($modUser));

        return parent::setModUser($modUser);
    }

    /**
     * {@inheritDoc}
     */
    public function getModUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModUser', array());

        return parent::getModUser();
    }

    /**
     * {@inheritDoc}
     */
    public function getSeqno()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getSeqno();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeqno', array());

        return parent::getSeqno();
    }

    /**
     * {@inheritDoc}
     */
    public function setClnSeqno(\AppBundle\Entity\ContainerLocalizations $clnSeqno = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClnSeqno', array($clnSeqno));

        return parent::setClnSeqno($clnSeqno);
    }

    /**
     * {@inheritDoc}
     */
    public function getClnSeqno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClnSeqno', array());

        return parent::getClnSeqno();
    }

    /**
     * {@inheritDoc}
     */
    public function getSpec2event()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSpec2event', array());

        return parent::getSpec2event();
    }

    /**
     * {@inheritDoc}
     */
    public function setSpec2event($spec2event)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSpec2event', array($spec2event));

        return parent::setSpec2event($spec2event);
    }

    /**
     * {@inheritDoc}
     */
    public function getEvent2Persons()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEvent2Persons', array());

        return parent::getEvent2Persons();
    }

    /**
     * {@inheritDoc}
     */
    public function setEvent2Persons($event2Persons)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEvent2Persons', array($event2Persons));

        return parent::setEvent2Persons($event2Persons);
    }

    /**
     * {@inheritDoc}
     */
    public function addEvent2Persons($event2Person)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEvent2Persons', array($event2Person));

        return parent::addEvent2Persons($event2Person);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEvent2Persons($event2Person)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEvent2Persons', array($event2Person));

        return parent::removeEvent2Persons($event2Person);
    }

    /**
     * {@inheritDoc}
     */
    public function setObservers(\Doctrine\Common\Collections\Collection $event2persons)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservers', array($event2persons));

        return parent::setObservers($event2persons);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservers', array());

        return parent::getObservers();
    }

    /**
     * {@inheritDoc}
     */
    public function addObservers($event2Person)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addObservers', array($event2Person));

        return parent::addObservers($event2Person);
    }

    /**
     * {@inheritDoc}
     */
    public function removeObservers($event2Person)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeObservers', array($event2Person));

        return parent::removeObservers($event2Person);
    }

    /**
     * {@inheritDoc}
     */
    public function setGatherers(\Doctrine\Common\Collections\Collection $event2persons)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGatherers', array($event2persons));

        return parent::setGatherers($event2persons);
    }

    /**
     * {@inheritDoc}
     */
    public function getGatherers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGatherers', array());

        return parent::getGatherers();
    }

    /**
     * {@inheritDoc}
     */
    public function addGatherers($event2Person)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addGatherers', array($event2Person));

        return parent::addGatherers($event2Person);
    }

    /**
     * {@inheritDoc}
     */
    public function removeGatherers($event2Person)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeGatherers', array($event2Person));

        return parent::removeGatherers($event2Person);
    }

    /**
     * {@inheritDoc}
     */
    public function setTime($time)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTime', array($time));

        return parent::setTime($time);
    }

    /**
     * {@inheritDoc}
     */
    public function getTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTime', array());

        return parent::getTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', array($date));

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', array());

        return parent::getDate();
    }

}
