taxa:
    resource: "@TaxaBundle/Resources/config/routing.yml"
    prefix:   /

marinemammals_observation:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation
