# you can read more about security in the related section of the documentation
# http://symfony.com/doc/current/book/security.html
security:
    # http://symfony.com/doc/current/book/security.html#encoding-the-user-s-password
    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext
        AppBundle\Entity\Users:
            algorithm: bcrypt

    # http://symfony.com/doc/current/book/security.html#hierarchical-roles
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        #chain_provider:
        #    chain:
        #        providers: [in_memory, user_db]
        #in_memory:
        #    memory:
        #        users:
        #            test: { password: test , roles: 'ROLE_ADMIN' }
        user_db:
            entity: { class: AppBundle:Users}


    # the main part of the security, where you can set up firewalls
    # for specific sections of your app
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern: ^/mgmt/login$
            #anonymous: ~
            security: false
        main:
            pattern: ^$|^/$
            anonymous: ~
            #security: false
        admin:
            anonymous: false
            pattern: ^$|^/$ #^/mgmt
            provider: user_db
            form_login:
                login_path: mm_login
                check_path: mm_login_check
            logout:
                path:   /logout #/mgmt/logout
                target: /
    # with these settings you can restrict or allow access for different parts
    # of your application based on roles, ip, host or methods
    # http://symfony.com/doc/current/book/security.html#security-book-access-control-matching-options
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/mgmt, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }