# you can read more about security in the related section of the documentation
# http://symfony.com/doc/current/book/security.html
security:
    # http://symfony.com/doc/current/book/security.html#encoding-the-user-s-password
    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext
        AppBundle\Entity\Users:
            algorithm: bcrypt

    # http://symfony.com/doc/current/book/security.html#hierarchical-roles
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_AUTOPSY_MGR, ROLE_OBSERVATION_MGR, ROLE_SAMPLE_MGR, ROLE_USER]
        ROLE_AUTOPSY_MGR: [ROLE_SAMPLE_MGR, ROLE_USER]
        ROLE_OBSERVATION_MGR: ROLE_USER

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        #chain_provider:
        #    chain:
        #        providers: [in_memory, user_db]
        #in_memory:
        #    memory:
        #        users:
        #            test: { password: test , roles: 'ROLE_ADMIN' }
        user_db:
            entity: { class: AppBundle:Users}


    # the main part of the security, where you can set up firewalls
    # for specific sections of your app
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:    ^/
            anonymous: ~
            form_login:
                check_path: /login_check
                login_path: /login
            logout:
                path:   /logout
                target: /
    # with these settings you can restrict or allow access for different parts
    # of your application based on roles, ip, host or methods
    # http://symfony.com/doc/current/book/security.html#security-book-access-control-matching-options
    access_control:
        - { path: ^$|^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/mgmt/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/mgmt, roles: ROLE_ADMIN }
        - { path: ^/tissuebank, roles: ROLE_ADMIN }
        - { path: ^/tissuebank, roles: ROLE_USER }
        - { path: ^/mgmt/necropsies/add, roles: ROLE_AUTOPSY_MGR }
        - { path: ^/mgmt/observations/add, roles: ROLE_OBSERVATION_MGR }
        - { path: ^/mgmt/observations/import, roles: ROLE_OBSERVATION_MGR }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }