# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
services:
    choice_type_extension:
        class: AppBundle\Form\Extension\ChoiceDescriptionExtension
        tags:
            - { name: form.type_extension, alias: choice }
    type.stationstype:
        class: AppBundle\Form\StationsType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: stationstype }

    type.placestype:
        class: AppBundle\Form\PlacesType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: placestype }

    type.platformstype:
        class: AppBundle\Form\PlatformsType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: platformstype }

    type.personstype:
        class: AppBundle\Form\PersonsType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: personstype }

    type.institutestype:
        class: AppBundle\Form\InstitutesType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: institutestype }

    type.sourcestype:
        class: AppBundle\Form\SourcesType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: sourcestype }

    type.taxatype:
        class: AppBundle\Form\TaxaType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: taxatype }

    type.specimen_selector:
        class: AppBundle\Form\SpecimensSelectorType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: specimen_selector }

    validator.node.areatype_indb:
        class: AppBundle\Validator\Constraints\LegalAreaTypeValidator
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: validator.constraint_validator, alias: areatype_indb }

    validator.node.coordinateprecisionflag_indb:
        class: AppBundle\Validator\Constraints\LegalCoordinatePrecisionFlagValidator
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: validator.constraint_validator, alias: coordinateprecisionflag_indb }

    validator.node.eventdatetimeflag_indb:
        class: AppBundle\Validator\Constraints\LegalEventDatetimeFlagValidator
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: validator.constraint_validator, alias: eventdatetimeflag_indb }

    validator.node.mediatype_indb:
        class: AppBundle\Validator\Constraints\LegalMediaTypeValidator
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: validator.constraint_validator, alias: mediatype_indb }

    validator.node.osntype_indb:
        class: AppBundle\Validator\Constraints\LegalOsnTypeValidator
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: validator.constraint_validator, alias: osntype_indb }

    validator.node.parametermethodorigin_indb:
        class: AppBundle\Validator\Constraints\LegalParameterMethodOriginValidator
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: validator.constraint_validator, alias: parametermethodorigin_indb }

    validator.node.persontitle_indb:
        class: AppBundle\Validator\Constraints\LegalPersonTitleValidator
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: validator.constraint_validator, alias: persontitle_indb }

    validator.node.pfmtype_indb:
        class: AppBundle\Validator\Constraints\LegalPfmTypeValidator
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: validator.constraint_validator, alias: pfmtype_indb }

    validator.node.placetype_indb:
        class: AppBundle\Validator\Constraints\LegalPlaceTypeValidator
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: validator.constraint_validator, alias: placetype_indb }

    validator.node.requestloanstatus_indb:
        class: AppBundle\Validator\Constraints\LegalRequestLoanStatusValidator
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: validator.constraint_validator, alias: requestloanstatus_indb }

    validator.node.samplingeffort_indb:
        class: AppBundle\Validator\Constraints\LegalSamplingEffortValidator
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: validator.constraint_validator, alias: samplingeffort_indb }

    validator.node.sex_indb:
        class: AppBundle\Validator\Constraints\LegalSexValidator
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: validator.constraint_validator, alias: sex_indb }

    validator.node.sourcetype_indb:
        class: AppBundle\Validator\Constraints\LegalSourceTypeValidator
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: validator.constraint_validator, alias: sourcetype_indb }
 #   app.exception_listener:
 #       class: AppBundle\Listener\ExceptionListener
 #       arguments: [@templating]
 #       tags:
 #           - { name: kernel.event_listener, event: kernel.exception, method: onKernelException}
    observations_provider:
        class: AppBundle\ControllerHelper\ObservationProvider
        arguments: [@doctrine.orm.entity_manager]