mm_homepage:
    pattern:  /
    defaults: { _controller: AppBundle:Page:index }
    requirements:
        _method:  GET

mm_homepage:
    pattern:  /index
    defaults: { _controller: AppBundle:Page:index }
    requirements:
        _method:  GET

mm_login:
    pattern:  /login
    defaults: { _controller: AppBundle:Security:login }
    requirements:
        _method:  GET

mm_login_check:
    pattern:  /login_check
    defaults: { _controller: AppBundle:Security:loginCheck }
    requirements:
        _method:  POST

mm_observations_about:
    pattern:  /observations/about
    defaults: { _controller: AppBundle:Page:aboutObservations }
    requirements:
        _method:  GET

mm_necropsies_about:
    pattern:  /necropsies/about
    defaults: { _controller: AppBundle:Page:aboutNecropsies }
    requirements:
        _method:  GET

mm_samples_about:
    pattern:  /samples/about
    defaults: { _controller: AppBundle:Page:aboutBiobank }
    requirements:
        _method:  GET

mm_observations_index:
    pattern:  /observations
    defaults: { _controller: AppBundle:ObservationsRetrieval:index }
    requirements:
        _method:  GET

mm_observations_mgmtindex:
    pattern:  /mgmt/observations
    defaults: { _controller: AppBundle:ObservationsRetrieval:mgmtIndex }
    requirements:
        _method:  GET

mm_observations_filter:
    pattern:  /observations/filtered
    defaults: { _controller: AppBundle:ObservationsRetrieval:filter }
    requirements:
        _method:  GET

mm_observations_mgmtfilter:
    pattern:  /mgmt/observations/filtered
    defaults: { _controller: AppBundle:ObservationsRetrieval:mgmtFilter }
    requirements:
        _method:  GET

mm_observed_specimens_mgmtindex:
    pattern:  /ajax/observed-specimens
    defaults: { _controller: AppBundle:ObservationsRetrieval:ajaxIndexSpecimen }
    requirements:
        _method:  GET

mm_observed_specimens_mgmtfilter:
    pattern:  /ajax/observed-specimens/filtered
    defaults: { _controller: AppBundle:ObservationsRetrieval:ajaxFilterSpecimen }
    requirements:
        _method:  GET

mm_observations_jsonexport:
    pattern:  /observations/json
    defaults: { _controller: AppBundle:ObservationsRetrieval:jsonExport }
    requirements:
        _method:  GET

mm_observations_mgmtjsonexport:
    pattern:  /mgmt/observations/json
    defaults: { _controller: AppBundle:ObservationsRetrieval:mgmtJsonExport }
    requirements:
        _method:  GET

mm_observations_view:
    pattern:  /observations/view/{id}
    defaults: { _controller: AppBundle:ObservationsRetrieval:view }
    requirements:
        _method:  GET

mm_observations_mgmtview:
    pattern:  mgmt/observations/view/{id}
    defaults: { _controller: AppBundle:ObservationsRetrieval:mgmtView }
    requirements:
        _method:  GET

mm_taxa_add_new:
    pattern:  /mgmt/taxa/add
    defaults: { _controller: AppBundle:Taxa:new }
    requirements:
        _method:  GET

mm_taxa_add_create:
    pattern:  /mgmt/taxa/add
    defaults: { _controller: AppBundle:Taxa:create }
    requirements:
        _method:  POST

mm_persons_add_new:
    pattern:  /mgmt/persons/add
    defaults: { _controller: AppBundle:Persons:new }
    requirements:
        _method:  GET

mm_persons_add_create:
    pattern:  /mgmt/persons/add
    defaults: { _controller: AppBundle:Persons:create }
    requirements:
        _method:  POST

mm_stations_add_new:
    pattern:  /mgmt/stations/add
    defaults: { _controller: AppBundle:Stations:new }
    requirements:
        _method:  GET

mm_stations_add_create:
    pattern:  /mgmt/stations/add
    defaults: { _controller: AppBundle:Stations:create }
    requirements:
        _method:  POST

mm_platforms_add_new:
    pattern:  /mgmt/platforms/add
    defaults: { _controller: AppBundle:Platforms:new }
    requirements:
        _method:  GET

mm_platforms_add_create:
    pattern:  /mgmt/platforms/add
    defaults: { _controller: AppBundle:Platforms:create }
    requirements:
        _method:  POST

mm_sources_add_new:
    pattern:  /mgmt/sources/add
    defaults: { _controller: AppBundle:Sources:new }
    requirements:
        _method:  GET

mm_sources_add_create:
    pattern:  /mgmt/sources/add
    defaults: { _controller: AppBundle:Sources:create }
    requirements:
        _method:  POST

mm_observations_add_new:
    pattern:  /mgmt/observations/add
    defaults: { _controller: AppBundle:Observations:new }
    requirements:
        _method:  GET

mm_observations_add_create:
    pattern:  /mgmt/observations/add
    defaults: { _controller: AppBundle:Observations:create }
    requirements:
        _method:  POST

mm_necropsies_new_edit:
    pattern:  /mgmt/necropsies/add-edit
    defaults: { _controller: AppBundle:Necropsies:newedit }
    requirements:
        _method:  GET

mm_necropsies_photo_upload:
    pattern:  /mgmt/necropsies/add-edit
    defaults: { _controller: AppBundle:Necropsies:newedit }
    requirements:
        _method:  POST

mm_samples_view_old:
    pattern:  /samples/old
    defaults: { _controller: AppBundle:Samples:indexOld }
    requirements:
        _method:  GET

mm_samples_view:
    pattern:  /samples/biobank
    defaults: { _controller: AppBundle:Samples:index }
    requirements:
        _method:  GET

mm_request_add_create:
    pattern:  /samples/biobank/requests/add
    defaults: { _controller: AppBundle:RequestLoans:create }
    requirements:
        _method:  POST

mm_request_edit:
    pattern:  /samples/biobank/requests/update/{id}
    defaults: { _controller: AppBundle:RequestLoans:update }
    requirements:
        _method:  GET

mm_request_view:
    pattern:  /samples/biobank/requests/view/{id}
    defaults: { _controller: AppBundle:RequestLoans:view }
    requirements:
        _method:  GET

mm_request_view_current:
    pattern:  /samples/biobank/requests/viewcurrent
    defaults: { _controller: AppBundle:RequestLoans:viewCurrent }
    requirements:
        _method:  GET

mm_observations_edit:
    pattern:  /mgmt/observations/update/{id}
    defaults: { _controller: AppBundle:Observations:edit }
    requirements:
        _method:  GET

mm_observations_update:
    pattern:  /mgmt/observations/update/{id}
    defaults: { _controller: AppBundle:Observations:update }
    requirements:
        _method:  POST

mm_ajax_scnNumber:
    pattern:  /ajax/scnnumber/{id}
    defaults: { _controller: AppBundle:Ajax:scnNumber }
    requirements:
        _method:  GET

mm_ajax_scnExists:
    pattern:  /ajax/scnexists/{id}
    defaults: { _controller: AppBundle:Ajax:scnExists}
    requirements:
        _method:  GET

mm_ajax_scn:
    pattern:  /ajax/scn/{id}
    defaults: { _controller: AppBundle:Ajax:scn}
    requirements:
        _method:  GET